### ISSUE TITLE
RuntimeError: cuda runtime error (59) 

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [zysite/parser#1]
**Hello, I run your code locally when the code runs the training, validation, and testing correctly. But the following error occurs while running on the server: (Note: My data label category is 2)**

THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMath.cu line=26 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "run.py", line 112, in <module>
    file=args.file)
  File "/home/workspace/dependency-parser/BiaffineAttention/biaffine/trainer.py", line 27, in fit
    self.train(train_loader)
  File "/home/workspace/dependency-parser/BiaffineAttention/biaffine/trainer.py", line 68, in train
    loss.backward()
  File "/home/miniconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/miniconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:26
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long                                    *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long                                    *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.

**Comment by zysite** [comment]
I just ran the code and I did not get this error
maybe you can refer to this issue(pytorch/pytorch#1204) to find a solution

**Comment by xiaoxiaoAurora** [comment]
Thank you! I found and solved this problem. In the classes of heads of the test data, there is  a  class setting to  -1， so the above error occurred.   **In addition, I would like to know that your code reports the following error， and how can i solve it.**  Thank you very much !

Traceback (most recent call last):
  File "F:/workspace/dependency_parser/BiaffineAttention/run.py", line 112, in <module>
    file=args.file)
  File "F:\workspace\dependency_parser\BiaffineAttention\biaffine\trainer.py", line 34, in fit
    loss, test_metric = self.evaluate(test_loader)
  File "E:\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 46, in decorate_no_grad
    return func(*args, **kwargs)
  File "F:\workspace\dependency_parser\BiaffineAttention\biaffine\trainer.py", line 85, in evaluate
    loss += self.model.get_loss(s_arc, s_lab, heads, labels, mask)
  File "F:\workspace\dependency_parser\BiaffineAttention\biaffine\parser.py", line 111, in get_loss
    s_lab = s_lab[torch.arange(len(s_arc)), heads]
RuntimeError: index 1214 is out of bounds for dimension 1 with size 21

**Comment by zysite** [comment]
Sorry, the code has not been completed yet and the repo still needs to be improved
Since I do not know which datasets you used, please note whether some configs have been modified correctly, such as the 'unk' token in pretrained embeddings
And can you tell me the shape of these tensors

**Comment by zysite** [comment]
> > Sorry, the code has not been completed yet and still needs to be improved😢
> > Since I do not know which datasets you used, please note whether some configs have been modified correctly, such as the 'unk' token in pretrained embeddings
> > And can you tell me the shape of these tensors
> 
> the data as the following:
> 
> 1	我	我	_	_	_	3	_	_	_
> 2	终于	终于	_	_	_	3	_	_	_
> 3	写	写	_	_	_	12	_	_	_
> 4	完	完	_	_	_	3	_	_	_
> 5	了	了	_	_	_	3	_	_	_
> 6	这	这	_	_	_	7	_	_	_
> 7	篇文章	篇文章	_	_	_	3	_	_	_
> 8	，	，	_	_	_	3	_	_	_
> 9	所以	所以	_	_	_	12	_	_	_
> 10	我	我	_	_	_	12	_	_	_
> 11	很	很	_	_	_	12	_	_	_
> 12	困	困	_	_	_	0	root	_	_
> 13	。	。	_	_	_	12	_	_	_
> 
> 1	我	我	_	_	_	2	_	_	_
> 2	哥哥	哥哥	_	_	_	4	_	_	_
> 3	到底	到底	_	_	_	4	_	_	_
> 4	介绍	介绍	_	_	_	0	root	_	_
> 5	他	他	_	_	_	9	_	_	_
> 6	很	很	_	_	_	7	_	_	_
> 7	可爱	可爱	_	_	_	9	_	_	_
> 8	的	的	_	_	_	7	_	_	_
> 9	女朋友	女朋友	_	_	_	4	_	_	_
> 10	。	。	_	_	_	4	_	_	_
> 
> 1	我	我	_	_	_	2	_	_	_
> 2	重视	重视	_	_	_	0	root	_	_
> 3	我们	我们	_	_	_	5	_	_	_
> 4	的	的	_	_	_	3	_	_	_
> 5	友谊	友谊	_	_	_	2	_	_	_
> 6	很	很	_	_	_	7	_	_	_
> 7	高	高	_	_	_	5	_	_	_
> 8	！	！	_	_	_	2	_	_	_
> 
> 1	谁	谁	_	_	_	6	_	_	_
> 2	想	想	_	_	_	6	_	_	_
> 3	跟	跟	_	_	_	4	_	_	_
> 4	我	我	_	_	_	6	_	_	_
> 5	一起	一起	_	_	_	6	_	_	_
> 6	去	去	_	_	_	10	_	_	_
> 7	我	我	_	_	_	10	_	_	_
> 8	就	就	_	_	_	10	_	_	_
> 9	一起	一起	_	_	_	10	_	_	_
> 10	去	去	_	_	_	0	root	_	_
> 11	谁	谁	_	_	_	_	_	_	_
> 12	。	。	_	_	_	10	_	_	_
> 
> 1	我	我	_	_	_	2	_	_	_
> 2	相信	相信	_	_	_	0	root	_	_
> 3	，	，	_	_	_	7	_	_	_
> 4	这种	这种	_	_	_	5	_	_	_
> 5	经验	经验	_	_	_	7	_	_	_
> 6	将	将	_	_	_	7	_	_	_
> 7	帮助	帮助	_	_	_	13	_	_	_
> 8	我	我	_	_	_	13	_	_	_
> 9	在	在	_	_	_	12	_	_	_
> 10	未来	未来	_	_	_	12	_	_	_
> 11	的	的	_	_	_	10	_	_	_
> 12	职业	职业	_	_	_	13	_	_	_
> 13	活动	活动	_	_	_	2	_	_	_
> 14	。	。	_	_	_	2	_	_	_
> 
> 1	这家	这家	_	_	_	2	_	_	_
> 2	公司	公司	_	_	_	3	_	_	_
> 3	注册	注册	_	_	_	0	root	_	_
> 4	在	在	_	_	_	6	_	_	_
> 5	2014	2014	_	_	_	6	_	_	_
> 6	年	年	_	_	_	3	_	_	_
> 7	。	。	_	_	_	3	_	_	_
> 
> 1	我们	我们	_	_	_	2	_	_	_
> 2	谈到	谈到	_	_	_	0	root	_	_
> 3	了	了	_	_	_	2	_	_	_
> 4	前景	前景	_	_	_	9	_	_	_
> 5	的	的	_	_	_	4	_	_	_
> 6	进一步	进一步	_	_	_	7	_	_	_
> 7	工作	工作	_	_	_	9	_	_	_
> 8	的	的	_	_	_	7	_	_	_
> 9	公司	公司	_	_	_	2	_	_	_
> 10	。	。	_	_	_	2	_	_	_
> 
> 1	该	该	_	_	_	2	_	_	_
> 2	公司	公司	_	_	_	7	_	_	_
> 3	是	是	_	_	_	7	_	_	_
> 4	很	很	_	_	_	5	_	_	_
> 5	欢快	欢快	_	_	_	7	_	_	_
> 6	的	的	_	_	_	5	_	_	_
> 7	工作人员	工作人员	_	_	_	0	root	_	_
> 8	。	。	_	_	_	7	_	_	_
> 
> 1	该	该	_	_	_	2	_	_	_
> 2	代表	代表	_	_	_	7	_	_	_
> 3	语言	语言	_	_	_	4	_	_	_
> 4	愉快	愉快	_	_	_	7	_	_	_
> 5	地	地	_	_	_	4	_	_	_
> 6	去	去	_	_	_	7	_	_	_
> 7	接触	接触	_	_	_	0	root	_	_
> 8	，	，	_	_	_	11	_	_	_
> 9	是	是	_	_	_	11	_	_	_
> 10	非常	非常	_	_	_	11	_	_	_
> 11	友好	友好	_	_	_	7	_	_	_
> 12	。	。	_	_	_	7	_	_	_
> 
> 1	我	我	_	_	_	4	_	_	_
> 2	真的	真的	_	_	_	4	_	_	_
> 3	很	很	_	_	_	4	_	_	_
> 4	喜欢	喜欢	_	_	_	0	root	_	_
> 5	在	在	_	_	_	6	_	_	_
> 6	实践	实践	_	_	_	9	_	_	_
> 7	中	中	_	_	_	6	_	_	_
> 8	的	的	_	_	_	6	_	_	_
> 9	公司	公司	_	_	_	4	_	_	_
> 10	。	。	_	_	_	4	_	_	_
> 
> 1	第一天	第一天	_	_	_	3	_	_	_
> 2	我	我	_	_	_	3	_	_	_
> 3	会见	会见	_	_	_	0	root	_	_
> 4	了	了	_	_	_	3	_	_	_
> 5	老板	老板	_	_	_	3	_	_	_
> 6	，	，	_	_	_	3	_	_	_
> 7	看到	看到	_	_	_	3	_	_	_
> 8	该	该	_	_	_	9	_	_	_
> 9	办公室	办公室	_	_	_	7	_	_	_
> 10	。	。	_	_	_	7	_	_	_
> 
> 1	在	在	_	_	_	3	_	_	_
> 2	实习	实习	_	_	_	3	_	_	_
> 3	期间	期间	_	_	_	6	_	_	_
> 4	，	，	_	_	_	3	_	_	_
> 5	我	我	_	_	_	6	_	_	_
> 6	进行	进行	_	_	_	0	root	_	_
> 7	各种类型	各种类型	_	_	_	9	_	_	_
> 8	的	的	_	_	_	7	_	_	_
> 9	工作	工作	_	_	_	6	_	_	_
> 10	。	。	_	_	_	6	_	_	_
> 
> 1	他	他	_	_	_	2	_	_	_
> 2	相信	相信	_	_	_	0	root	_	_
> 3	在	在	_	_	_	4	_	_	_
> 4	未来	未来	_	_	_	2	_	_	_
> 5	，	，	_	_	_	7	_	_	_
> 6	他	他	_	_	_	7	_	_	_
> 7	争取	争取	_	_	_	2	_	_	_
> 8	很	很	_	_	_	9	_	_	_
> 9	好	好	_	_	_	11	_	_	_
> 10	的	的	_	_	_	9	_	_	_
> 11	职务	职务	_	_	_	7	_	_	_
> 12	和	和	_	_	_	15	_	_	_
> 13	更	更	_	_	_	14	_	_	_
> 14	高	高	_	_	_	15	_	_	_
> 15	工资	工资	_	_	_	11	_	_	_
> 16	。	。	_	_	_	2	_	_	_

just make sure that the 1,6,7 columns represent the words heads labels respectively

**Comment by xiaoxiaoAurora** [comment]
> > > Sorry, the code has not been completed yet and still needs to be improved😢
> > > Since I do not know which datasets you used, please note whether some configs have been modified correctly, such as the 'unk' token in pretrained embeddings
> > > And can you tell me the shape of these tensors
> > 
> > 
> > the data as the following:
> > 1	我	我	_	_	_	3	_	_	_
> > 2	终于	终于	_	_	_	3	_	_	_
> > 3	写	写	_	_	_	12	_	_	_
> > 4	完	完	_	_	_	3	_	_	_
> > 5	了	了	_	_	_	3	_	_	_
> > 6	这	这	_	_	_	7	_	_	_
> > 7	篇文章	篇文章	_	_	_	3	_	_	_
> > 8	，	，	_	_	_	3	_	_	_
> > 9	所以	所以	_	_	_	12	_	_	_
> > 10	我	我	_	_	_	12	_	_	_
> > 11	很	很	_	_	_	12	_	_	_
> > 12	困	困	_	_	_	0	root	_	_
> > 13	。	。	_	_	_	12	_	_	_
> > 1	我	我	_	_	_	2	_	_	_
> > 2	哥哥	哥哥	_	_	_	4	_	_	_
> > 3	到底	到底	_	_	_	4	_	_	_
> > 4	介绍	介绍	_	_	_	0	root	_	_
> > 5	他	他	_	_	_	9	_	_	_
> > 6	很	很	_	_	_	7	_	_	_
> > 7	可爱	可爱	_	_	_	9	_	_	_
> > 8	的	的	_	_	_	7	_	_	_
> > 9	女朋友	女朋友	_	_	_	4	_	_	_
> > 10	。	。	_	_	_	4	_	_	_
> > 1	我	我	_	_	_	2	_	_	_
> > 2	重视	重视	_	_	_	0	root	_	_
> > 3	我们	我们	_	_	_	5	_	_	_
> > 4	的	的	_	_	_	3	_	_	_
> > 5	友谊	友谊	_	_	_	2	_	_	_
> > 6	很	很	_	_	_	7	_	_	_
> > 7	高	高	_	_	_	5	_	_	_
> > 8	！	！	_	_	_	2	_	_	_
> > 1	谁	谁	_	_	_	6	_	_	_
> > 2	想	想	_	_	_	6	_	_	_
> > 3	跟	跟	_	_	_	4	_	_	_
> > 4	我	我	_	_	_	6	_	_	_
> > 5	一起	一起	_	_	_	6	_	_	_
> > 6	去	去	_	_	_	10	_	_	_
> > 7	我	我	_	_	_	10	_	_	_
> > 8	就	就	_	_	_	10	_	_	_
> > 9	一起	一起	_	_	_	10	_	_	_
> > 10	去	去	_	_	_	0	root	_	_
> > 11	谁	谁	_	_	_	_	_	_	_
> > 12	。	。	_	_	_	10	_	_	_
> > 1	我	我	_	_	_	2	_	_	_
> > 2	相信	相信	_	_	_	0	root	_	_
> > 3	，	，	_	_	_	7	_	_	_
> > 4	这种	这种	_	_	_	5	_	_	_
> > 5	经验	经验	_	_	_	7	_	_	_
> > 6	将	将	_	_	_	7	_	_	_
> > 7	帮助	帮助	_	_	_	13	_	_	_
> > 8	我	我	_	_	_	13	_	_	_
> > 9	在	在	_	_	_	12	_	_	_
> > 10	未来	未来	_	_	_	12	_	_	_
> > 11	的	的	_	_	_	10	_	_	_
> > 12	职业	职业	_	_	_	13	_	_	_
> > 13	活动	活动	_	_	_	2	_	_	_
> > 14	。	。	_	_	_	2	_	_	_
> > 1	这家	这家	_	_	_	2	_	_	_
> > 2	公司	公司	_	_	_	3	_	_	_
> > 3	注册	注册	_	_	_	0	root	_	_
> > 4	在	在	_	_	_	6	_	_	_
> > 5	2014	2014	_	_	_	6	_	_	_
> > 6	年	年	_	_	_	3	_	_	_
> > 7	。	。	_	_	_	3	_	_	_
> > 1	我们	我们	_	_	_	2	_	_	_
> > 2	谈到	谈到	_	_	_	0	root	_	_
> > 3	了	了	_	_	_	2	_	_	_
> > 4	前景	前景	_	_	_	9	_	_	_
> > 5	的	的	_	_	_	4	_	_	_
> > 6	进一步	进一步	_	_	_	7	_	_	_
> > 7	工作	工作	_	_	_	9	_	_	_
> > 8	的	的	_	_	_	7	_	_	_
> > 9	公司	公司	_	_	_	2	_	_	_
> > 10	。	。	_	_	_	2	_	_	_
> > 1	该	该	_	_	_	2	_	_	_
> > 2	公司	公司	_	_	_	7	_	_	_
> > 3	是	是	_	_	_	7	_	_	_
> > 4	很	很	_	_	_	5	_	_	_
> > 5	欢快	欢快	_	_	_	7	_	_	_
> > 6	的	的	_	_	_	5	_	_	_
> > 7	工作人员	工作人员	_	_	_	0	root	_	_
> > 8	。	。	_	_	_	7	_	_	_
> > 1	该	该	_	_	_	2	_	_	_
> > 2	代表	代表	_	_	_	7	_	_	_
> > 3	语言	语言	_	_	_	4	_	_	_
> > 4	愉快	愉快	_	_	_	7	_	_	_
> > 5	地	地	_	_	_	4	_	_	_
> > 6	去	去	_	_	_	7	_	_	_
> > 7	接触	接触	_	_	_	0	root	_	_
> > 8	，	，	_	_	_	11	_	_	_
> > 9	是	是	_	_	_	11	_	_	_
> > 10	非常	非常	_	_	_	11	_	_	_
> > 11	友好	友好	_	_	_	7	_	_	_
> > 12	。	。	_	_	_	7	_	_	_
> > 1	我	我	_	_	_	4	_	_	_
> > 2	真的	真的	_	_	_	4	_	_	_
> > 3	很	很	_	_	_	4	_	_	_
> > 4	喜欢	喜欢	_	_	_	0	root	_	_
> > 5	在	在	_	_	_	6	_	_	_
> > 6	实践	实践	_	_	_	9	_	_	_
> > 7	中	中	_	_	_	6	_	_	_
> > 8	的	的	_	_	_	6	_	_	_
> > 9	公司	公司	_	_	_	4	_	_	_
> > 10	。	。	_	_	_	4	_	_	_
> > 1	第一天	第一天	_	_	_	3	_	_	_
> > 2	我	我	_	_	_	3	_	_	_
> > 3	会见	会见	_	_	_	0	root	_	_
> > 4	了	了	_	_	_	3	_	_	_
> > 5	老板	老板	_	_	_	3	_	_	_
> > 6	，	，	_	_	_	3	_	_	_
> > 7	看到	看到	_	_	_	3	_	_	_
> > 8	该	该	_	_	_	9	_	_	_
> > 9	办公室	办公室	_	_	_	7	_	_	_
> > 10	。	。	_	_	_	7	_	_	_
> > 1	在	在	_	_	_	3	_	_	_
> > 2	实习	实习	_	_	_	3	_	_	_
> > 3	期间	期间	_	_	_	6	_	_	_
> > 4	，	，	_	_	_	3	_	_	_
> > 5	我	我	_	_	_	6	_	_	_
> > 6	进行	进行	_	_	_	0	root	_	_
> > 7	各种类型	各种类型	_	_	_	9	_	_	_
> > 8	的	的	_	_	_	7	_	_	_
> > 9	工作	工作	_	_	_	6	_	_	_
> > 10	。	。	_	_	_	6	_	_	_
> > 1	他	他	_	_	_	2	_	_	_
> > 2	相信	相信	_	_	_	0	root	_	_
> > 3	在	在	_	_	_	4	_	_	_
> > 4	未来	未来	_	_	_	2	_	_	_
> > 5	，	，	_	_	_	7	_	_	_
> > 6	他	他	_	_	_	7	_	_	_
> > 7	争取	争取	_	_	_	2	_	_	_
> > 8	很	很	_	_	_	9	_	_	_
> > 9	好	好	_	_	_	11	_	_	_
> > 10	的	的	_	_	_	9	_	_	_
> > 11	职务	职务	_	_	_	7	_	_	_
> > 12	和	和	_	_	_	15	_	_	_
> > 13	更	更	_	_	_	14	_	_	_
> > 14	高	高	_	_	_	15	_	_	_
> > 15	工资	工资	_	_	_	11	_	_	_
> > 16	。	。	_	_	_	2	_	_	_
> 
> just make sure that the 1,6,7 columns represent the words heads labels respectively

That's great! Thank you very much for your answer, I found the reason, but for the time being did not think of a better solution to deal with this problem, thank you very much!
